
/*
 * Copyright (C) 2015 Dieter J Kybelksties
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 *
 * @date: 2015-12-16
 * @author: Dieter J Kybelksties
 */
package com.kybelksties.gui;

import java.awt.Color;
import java.awt.Font;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Logger;

/**
 *
 * @author kybelksd
 */
public class DebugComponentsFrame extends javax.swing.JFrame
{

    Color foregroundColor4 = Color.RED;
    Color foregroundColor5 = Color.GREEN;
    Color foregroundColor6 = Color.BLUE;

    /**
     * Creates new form TestColors
     */
    public DebugComponentsFrame()
    {
        initComponents();
        //      fontChooser2.setShowDateLabel(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        mainSplitPane = new javax.swing.JSplitPane();
        controlPanel = new javax.swing.JPanel();
        dateButton = new javax.swing.JButton();
        colorButton = new javax.swing.JButton();
        fontButton = new javax.swing.JButton();
        tablePanel = new javax.swing.JPanel();
        tableScrollPane = new javax.swing.JScrollPane();
        colorTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        mainSplitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        controlPanel.setMaximumSize(new java.awt.Dimension(213, 35));
        controlPanel.setPreferredSize(new java.awt.Dimension(213, 35));

        dateButton.setText(org.openide.util.NbBundle.getMessage(DebugComponentsFrame.class, "DebugComponentsFrame.dateButton.text")); // NOI18N
        dateButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                dateButtonActionPerformed(evt);
            }
        });
        controlPanel.add(dateButton);

        colorButton.setText(org.openide.util.NbBundle.getMessage(DebugComponentsFrame.class, "DebugComponentsFrame.colorButton.text")); // NOI18N
        colorButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                colorButtonActionPerformed(evt);
            }
        });
        controlPanel.add(colorButton);

        fontButton.setText(org.openide.util.NbBundle.getMessage(DebugComponentsFrame.class, "DebugComponentsFrame.fontButton.text")); // NOI18N
        fontButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                fontButtonActionPerformed(evt);
            }
        });
        controlPanel.add(fontButton);

        mainSplitPane.setBottomComponent(controlPanel);

        tablePanel.setLayout(new javax.swing.BoxLayout(tablePanel, javax.swing.BoxLayout.LINE_AXIS));

        colorTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String []
            {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableScrollPane.setViewportView(colorTable);

        tablePanel.add(tableScrollPane);

        mainSplitPane.setLeftComponent(tablePanel);

        getContentPane().add(mainSplitPane);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void colorButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_colorButtonActionPerformed
    {//GEN-HEADEREND:event_colorButtonActionPerformed
        ColorUtils.ContrastColorSet colSet =
                                    ForegroundBackgroundColorChooser.showDialog(
                                            this,
                                            Color.BLACK,
                                            128,
                                            true,
                                            Color.PINK,
                                            Color.CYAN,
                                            Color.MAGENTA);

        colorTable.setModel(colSet);
        repaint();
    }//GEN-LAST:event_colorButtonActionPerformed

    private void fontButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_fontButtonActionPerformed
    {//GEN-HEADEREND:event_fontButtonActionPerformed
        Font f = FontChooser.showDialog(this, null);
        System.out.println("Font=" + f.toString());
    }//GEN-LAST:event_fontButtonActionPerformed

    private void dateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateButtonActionPerformed
        Date f = DateChooser.showDialog(this, null, Locale.getDefault());
        System.out.println("Date=" + f.toString());
    }//GEN-LAST:event_dateButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info
                         : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException | InstantiationException |
               IllegalAccessException |
               javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(DebugComponentsFrame.class.
                    getName()).log(
                            java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            @Override
            public void run()
            {
                new DebugComponentsFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton colorButton;
    private javax.swing.JTable colorTable;
    private javax.swing.JPanel controlPanel;
    private javax.swing.JButton dateButton;
    private javax.swing.JButton fontButton;
    private javax.swing.JSplitPane mainSplitPane;
    private javax.swing.JPanel tablePanel;
    private javax.swing.JScrollPane tableScrollPane;
    // End of variables declaration//GEN-END:variables
    private static final String CLASS_NAME =
                                DebugComponentsFrame.class.getName();
    private static final Logger LOGGER = Logger.getLogger(CLASS_NAME);
}
