/*
 * Copyright (C) 2015 Dieter J Kybelksties
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 *
 * @date: 2015-12-16
 * @author: Dieter J Kybelksties
 */
package com.kybelksties.gui;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Paint;
import java.awt.Point;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Logger;
import javax.swing.JPanel;

/**
 * A class to be used for debugging of visual components of this package.
 */
public class DebugComponentsFrame extends javax.swing.JFrame
{

    private static final Class CLAZZ = DebugComponentsFrame.class;
    private static final String CLASS_NAME = CLAZZ.getName();
    private static final Logger LOGGER = Logger.getLogger(CLASS_NAME);

    Color foregroundColor4 = Color.RED;
    Color foregroundColor5 = Color.GREEN;
    Color foregroundColor6 = Color.BLUE;
    private Object ColorUtils;

    /**
     * Creates new form TestColors
     */
    public DebugComponentsFrame()
    {
        initComponents();
        outputPanel1.showStyleSamples();
        outputPanel2.showStyleSamples();
        outputPanel1.setVisible(false);
        outputPanel2.setVisible(false);
        JPanel panel = new JPanel()
        {
            @Override
            public void paintComponent(Graphics g)
            {
                ((Graphics2D) g).setPaint(
                        new ColorUtils.RandomGridGradientPaint(new Point(0, 0),
                                                               new Point(30, 40),
                                                               10,
                                                               20,
                                                               7));
                g.fillOval(0, 0, 40, 50);
            }
        };
        panel.setPreferredSize(new Dimension(50, 50));
        add(panel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        mainSplitPane = new javax.swing.JSplitPane();
        controlPanel = new javax.swing.JPanel();
        dateButton = new javax.swing.JButton();
        fgBgColorButton = new javax.swing.JButton();
        fontButton = new javax.swing.JButton();
        datePicker1 = new com.kybelksties.gui.DatePicker();
        outputPanel1 = new com.kybelksties.gui.OutputPanel();
        outputPanel2 = new com.kybelksties.gui.OutputPanel();
        gradientButton = new javax.swing.JButton();
        timePicker1 = new com.kybelksties.gui.TimePicker();
        gradButton = new javax.swing.JButton();
        gradientTypeComboBox1 = new com.kybelksties.gui.GradientTypeComboBox();
        tablePanel = new javax.swing.JPanel();
        tableScrollPane = new javax.swing.JScrollPane();
        colorTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        mainSplitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        controlPanel.setMaximumSize(new java.awt.Dimension(213, 35));
        controlPanel.setPreferredSize(new java.awt.Dimension(213, 35));
        controlPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dateButton.setText(org.openide.util.NbBundle.getMessage(DebugComponentsFrame.class, "DebugComponentsFrame.dateButton.text")); // NOI18N
        dateButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                dateButtonActionPerformed(evt);
            }
        });
        controlPanel.add(dateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 5, -1, -1));

        fgBgColorButton.setText(org.openide.util.NbBundle.getMessage(DebugComponentsFrame.class, "DebugComponentsFrame.fgBgColorButton.text")); // NOI18N
        fgBgColorButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                fgBgColorButtonActionPerformed(evt);
            }
        });
        controlPanel.add(fgBgColorButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, -1, -1));

        fontButton.setText(org.openide.util.NbBundle.getMessage(DebugComponentsFrame.class, "DebugComponentsFrame.fontButton.text")); // NOI18N
        fontButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                fontButtonActionPerformed(evt);
            }
        });
        controlPanel.add(fontButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, -1, -1));
        controlPanel.add(datePicker1, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 7, -1, -1));

        outputPanel1.setDefaultBackground(new java.awt.Color(255, 255, 51));
        outputPanel1.setDefaultBold(java.lang.Boolean.TRUE);
        outputPanel1.setDefaultFontFamily(org.openide.util.NbBundle.getMessage(DebugComponentsFrame.class, "DebugComponentsFrame.outputPanel1.defaultFontFamily")); // NOI18N
        outputPanel1.setDefaultForeground(new java.awt.Color(0, 153, 51));
        controlPanel.add(outputPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 430, 70));

        outputPanel2.setDefaultBackground(new java.awt.Color(0, 204, 204));
        outputPanel2.setDefaultFontSize(new java.lang.Integer(18));
        outputPanel2.setDefaultForeground(new java.awt.Color(0, 0, 255));
        controlPanel.add(outputPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 430, 60));

        gradientButton.setText(org.openide.util.NbBundle.getMessage(DebugComponentsFrame.class, "DebugComponentsFrame.gradientButton.text")); // NOI18N
        gradientButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                gradientButtonActionPerformed(evt);
            }
        });
        controlPanel.add(gradientButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, -1, -1));
        controlPanel.add(timePicker1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, -1, -1));

        gradButton.setText(org.openide.util.NbBundle.getMessage(DebugComponentsFrame.class, "DebugComponentsFrame.gradButton.text")); // NOI18N
        controlPanel.add(gradButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, 130, 60));
        controlPanel.add(gradientTypeComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        mainSplitPane.setBottomComponent(controlPanel);

        tablePanel.setLayout(new javax.swing.BoxLayout(tablePanel, javax.swing.BoxLayout.LINE_AXIS));

        colorTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String []
            {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableScrollPane.setViewportView(colorTable);

        tablePanel.add(tableScrollPane);

        mainSplitPane.setLeftComponent(tablePanel);

        getContentPane().add(mainSplitPane);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fgBgColorButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_fgBgColorButtonActionPerformed
    {//GEN-HEADEREND:event_fgBgColorButtonActionPerformed
        ColorUtils.ContrastColorSet colSet =
                                    ForegroundBackgroundColorChooser.showDialog(
                                            this,
                                            Color.BLACK,
                                            128,
                                            true,
                                            Color.PINK,
                                            Color.CYAN,
                                            Color.MAGENTA);

        colorTable.setModel(colSet);
        repaint();
    }//GEN-LAST:event_fgBgColorButtonActionPerformed

    private void fontButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_fontButtonActionPerformed
    {//GEN-HEADEREND:event_fontButtonActionPerformed
        Font f = FontChooser.showDialog(this, null);
        System.out.println("Font=" + f.toString());
    }//GEN-LAST:event_fontButtonActionPerformed

    private void dateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateButtonActionPerformed
        Date f = DateChooser.showDialog(this, null, Locale.getDefault());
        System.out.println("Date=" + f.toString());
    }//GEN-LAST:event_dateButtonActionPerformed

    private void gradientButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_gradientButtonActionPerformed
    {//GEN-HEADEREND:event_gradientButtonActionPerformed
        Paint gradient = GradientColorChooser.showDialog(this,
                                                         Color.CYAN,
                                                         Color.MAGENTA);

        repaint();
    }//GEN-LAST:event_gradientButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info
                         : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException | InstantiationException |
               IllegalAccessException |
               javax.swing.UnsupportedLookAndFeelException ex)
        {
            LOGGER.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            @Override
            public void run()
            {
                new DebugComponentsFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable colorTable;
    private javax.swing.JPanel controlPanel;
    private javax.swing.JButton dateButton;
    private com.kybelksties.gui.DatePicker datePicker1;
    private javax.swing.JButton fgBgColorButton;
    private javax.swing.JButton fontButton;
    private javax.swing.JButton gradButton;
    private javax.swing.JButton gradientButton;
    private com.kybelksties.gui.GradientTypeComboBox gradientTypeComboBox1;
    private javax.swing.JSplitPane mainSplitPane;
    private com.kybelksties.gui.OutputPanel outputPanel1;
    private com.kybelksties.gui.OutputPanel outputPanel2;
    private javax.swing.JPanel tablePanel;
    private javax.swing.JScrollPane tableScrollPane;
    private com.kybelksties.gui.TimePicker timePicker1;
    // End of variables declaration//GEN-END:variables
}
