/*
 * @author  Dieter J Kybelksties
 * @date Sep 23, 2016
 *
 */
package com.kybelksties.gui;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.MultipleGradientPaint;
import java.awt.Point;
import javax.swing.JPanel;

/**
 *
 * @author Dieter J Kybelksties
 */
public class GradientFrame extends javax.swing.JFrame
{

    /**
     * Creates new form GradientFrame
     */
    public GradientFrame()
    {
        initComponents();
        JPanel panel = new JPanel()
        {
            @Override
            public void paintComponent(Graphics g)
            {
//                ((Graphics2D) g).setPaint(
//                        new ColorUtils.RandomGridGradientPaint(new Point(0, 0),
//                                                               new Point(30, 40),
//                                                               10,
//                                                               20,
//                                                               7));
                ((Graphics2D) g).setPaint(
                        new ColorUtils.FourColorGradientPaint(
                                new Point(0, 0),
                                new Point(60, 80),
                                Color.RED,
                                Color.GREEN,
                                Color.BLUE,
                                Color.YELLOW,
                                MultipleGradientPaint.CycleMethod.NO_CYCLE));
                g.fillOval(0, 0, 150, 150);
            }
        };
        panel.setPreferredSize(new Dimension(200, 200));
        add(panel);
        setPreferredSize(new Dimension(300, 300));
        setMinimumSize(new Dimension(200, 200));
        setBounds(700, 700, 200, 200);
    }

    /**
     * This method is called from within the constructor to initialise the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info
                         : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(GradientFrame.class.getName()).
                    log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(GradientFrame.class.getName()).
                    log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(GradientFrame.class.getName()).
                    log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(GradientFrame.class.getName()).
                    log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            @Override
            public void run()
            {
                new GradientFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
